
import { GoogleGenAI } from "@google/genai";
import { RSSFeed, RSSItem, GroundingSource } from "../types";

const extractJSON = (text: string) => {
  try {
    const jsonMatch = text.match(/```json\s*([\s\S]*?)\s*```/) || text.match(/\{[\s\S]*\}/);
    const cleanText = jsonMatch ? (jsonMatch[1] || jsonMatch[0]) : text;
    return JSON.parse(cleanText.trim());
  } catch (e) {
    console.error("JSON Parsing failed:", e);
    return null;
  }
};

/**
 * Scrapes a social media profile using Gemini with Google Search grounding.
 */
export const scrapeProfile = async (profileUrl: string, modelName: string = "gemini-3-flash-preview"): Promise<RSSFeed> => {
  if (!process.env.API_KEY || process.env.API_KEY === "undefined") {
    throw new Error("API_KEY_MISSING");
  }

  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  const prompt = `
    Lütfen şu sosyal medya profilini araştır: "${profileUrl}"
    Google Search kullanarak bu profilin en güncel 5 gönderisini bul.
    
    Yanıtını SADECE aşağıdaki JSON yapısında, markdown kod bloğu içinde ver:
    
    {
      "title": "Profil Başlığı",
      "description": "Profil Özeti",
      "items": [
        {
          "title": "Gönderi başlığı (Türkçe)",
          "link": "Gönderi direkt URL",
          "description": "Gönderi içeriği özeti (Türkçe)",
          "pubDate": "ISO formatında tarih",
          "author": "Yazar adı",
          "imageUrl": "Varsa görsel URL"
        }
      ]
    }
  `;

  try {
    const response = await ai.models.generateContent({
      model: modelName,
      contents: prompt,
      config: {
        tools: [{ googleSearch: {} }],
      },
    });

    const result = extractJSON(response.text || "");
    
    const chunks = response.candidates?.[0]?.groundingMetadata?.groundingChunks;
    const sources: GroundingSource[] = [];
    if (chunks) {
      chunks.forEach((chunk: any) => {
        if (chunk.web && chunk.web.uri) {
          sources.push({ title: chunk.web.title || "Kaynak", uri: chunk.web.uri });
        }
      });
    }

    if (!result || !result.items) {
      throw new Error("INVALID_RESPONSE");
    }
    
    return {
      title: result.title || "Sosyal Medya Beslemesi",
      description: result.description || "Takip edilen profil",
      link: profileUrl,
      lastBuildDate: new Date().toISOString(),
      items: result.items.map((item: any) => ({
        ...item,
        pubDate: item.pubDate || new Date().toISOString(),
        sources: sources.length > 0 ? sources : undefined
      }))
    };
  } catch (error: any) {
    const errorStr = JSON.stringify(error);
    console.error("Scraping failed detailed:", errorStr);
    
    if (errorStr.includes("429") || errorStr.includes("RESOURCE_EXHAUSTED")) {
      throw new Error("RATE_LIMIT_EXCEEDED");
    }
    if (errorStr.includes("401")) throw new Error("API_KEY_INVALID");
    if (errorStr.includes("403")) throw new Error("API_KEY_PERMISSION_DENIED");
    
    throw error;
  }
};

/**
 * Generates an RSS 2.0 compatible XML string from a list of RSS items.
 */
export const generateUnifiedRSS = (items: RSSItem[]): string => {
  const sortedItems = [...items].sort((a, b) => 
    new Date(b.pubDate).getTime() - new Date(a.pubDate).getTime()
  );

  const itemsXML = sortedItems.map(item => {
    let safeDate = new Date().toUTCString();
    try { safeDate = new Date(item.pubDate).toUTCString(); } catch {}

    const descriptionWithImage = item.imageUrl 
      ? `<img src="${item.imageUrl}" style="max-width:100%;"/><br/>${item.description}`
      : item.description;
    
    const sourceLinks = item.sources?.map(s => `<li><a href="${s.uri}">${s.title}</a></li>`).join('') || '';
    const footer = sourceLinks ? `<br/><br/><b>Doğrulama Kaynakları:</b><ul>${sourceLinks}</ul>` : '';

    return `
    <item>
      <title><![CDATA[${item.title}]]></title>
      <link>${item.link}</link>
      <description><![CDATA[${descriptionWithImage}${footer}]]></description>
      <pubDate>${safeDate}</pubDate>
      <author>${item.author}</author>
      <guid isPermaLink="false">${item.link + (item.imageUrl || '')}</guid>
    </item>`;
  }).join('');

  return `<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0">
  <channel>
    <title>Social2RSS Feed</title>
    <link>https://social2rss.local</link>
    <description>Generated by Gemini AI</description>
    <lastBuildDate>${new Date().toUTCString()}</lastBuildDate>
    <language>tr-tr</language>
    ${itemsXML}
  </channel>
</rss>`;
};
